name: octoprint-pfs
base: core18
version: '1.4.0'
summary: The snappy web interface for your 3D printer
description: |
  Control and monitor every aspect of your 3D printer and your printing jobs
  right from within your browser. OctoPrint is compatible with most of the
  available consumer 3D printers.
grade: stable
confinement: strict

apps:
  daemon:
    environment:
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    command: bin/octoprint serve --iknowwhatimdoing --basedir /etc/octoprint
    plugs: [home, network-bind]
    daemon: simple

parts:
  octoprint:
    plugin: python
    python-version: python3
    source: .

layout:
  /etc/octoprint:
    bind: $SNAP_COMMON/basedir
  $SNAP/usr/lib/python3/dist-packages:
    bind: $SNAP_COMMON/dist-packages
  $SNAP/usr/local/lib/python3/dist-packages:
    bind: $SNAP_COMMON/dist-packages-local

slots:
  s0:
    interface: serial-port
    path: /dev/ttyS0
  acm0:
    interface: serial-port
    path: /dev/ttyACM0
